account:
  balance:
    current:
      corporate:
        max: 1000000
        mean: 300000
        min: 100000
        std_dev: 200000
      personal:
        max: 5000000
        mean: 25000
        min: 10000
        std_dev: 15000
    fixed:
      corporate:
        max: 5000000
        mean: 1500000
        min: 500000
        std_dev: 1000000
      personal:
        max: 200000
        mean: 100000
        min: 50000
        std_dev: 50000
    loan:
      corporate:
        max: 10000000
        mean: 2000000
        min: 500000
        std_dev: 1500000
      personal:
        max: 500000
        mean: 150000
        min: 50000
        std_dev: 100000
  count_per_customer:
    corporate:
      mean: 3.2
      std_dev: 0.8
    personal:
      mean: 2.0
      std_dev: 0.5
    vip_multiplier: 1.4
  currency_distribution:
    CNY: 0.88
    EUR: 0.02
    GBP: 0.01
    JPY: 0.01
    USD: 0.08
  status_distribution:
    active: 0.75
    closed: 0.03
    dormant: 0.18
    frozen: 0.04
  type_distribution:
    current: 0.65
    fixed: 0.25
    loan: 0.1
anomaly:
  account_anomaly:
    abnormal_login_rate: 0.0055
    password_error_rate: 0.02
    temporary_freeze_rate: 0.0075
  system_anomaly:
    maintenance_period:
      transaction_reduction: 0.85
    peak_period:
      congestion_rate: 0.075
    upgrade_period:
      transaction_fluctuation: 0.4
  transaction_anomaly:
    duplicate_rate: 0.005
    failure_rate: 0.02
    timeout_rate: 0.01
app_user:
  activity_level:
    high:
      ratio: 0.35
      weekly_usage:
      - 3
      - 7
    inactive:
      ratio: 0.1
    low:
      monthly_usage:
      - 1
      - 3
      ratio: 0.2
    medium:
      ratio: 0.35
      weekly_usage:
      - 1
      - 2
  device_distribution:
    android: 0.5
    ios: 0.5
    tablet_ratio: 0.08
  feature_usage:
    account_query: 0.85
    investment: 0.35
    life_service: 0.25
    loan_service: 0.2
    transfer_payment: 0.65
  penetration_rate:
    age_factor:
      18-40: 0.8
      41-60: 0.5
      60+: 0.2
    corporate: 0.55
    personal: 0.65
channel_profile:
  channel_conversion:
    app_to_wechat:
      monthly_rate: 0.125
    offline_to_app:
      monthly_rate: 0.075
    wechat_to_work_wechat:
      monthly_rate: 0.055
  channel_count_distribution:
    single_channel: 0.25
    three_or_more: 0.3
    two_channels: 0.45
  channel_preference:
    age_18_35:
      electronic: 0.7
      offline: 0.3
    age_36_55:
      electronic: 0.5
      offline: 0.5
    age_56_plus:
      electronic: 0.3
      offline: 0.7
    corporate:
      online_banking: 0.6
      wechat: 0.2
customer:
  corporate:
    industry_distribution:
      finance: 0.05
      manufacturing: 0.25
      other: 0.15
      retail: 0.15
      service: 0.3
      technology: 0.1
    registered_capital:
      large:
        max: 1000000000
        min: 50000000
      medium:
        max: 50000000
        min: 5000000
      small:
        max: 5000000
        min: 500000
    size_distribution:
      large: 0.1
      medium: 0.3
      small: 0.6
  credit_score:
    distribution:
      average:
        range:
        - 500
        - 599
        ratio: 0.2
      excellent:
        range:
        - 700
        - 850
        ratio: 0.3
      good:
        range:
        - 600
        - 699
        ratio: 0.4
      poor:
        range:
        - 350
        - 499
        ratio: 0.1
    range:
      max: 850
      min: 350
    vip_bonus: 50
  personal:
    age_distribution:
      18-25: 0.15
      26-40: 0.4
      41-60: 0.35
      60+: 0.1
    annual_income:
      max: 300000
      mean: 60000
      min: 20000
      std_dev: 30000
    gender_distribution:
      female: 0.48
      male: 0.52
    occupation_distribution:
      administrative: 0.15
      manual_labor: 0.1
      professional: 0.25
      retired: 0.05
      sales: 0.1
      service: 0.2
      technical: 0.15
  relationship:
    acquisition_channel:
      branch: 0.5
      online: 0.3
      other: 0.05
      referral: 0.15
    manager_customer_ratio:
      regular:
        max: 200
        min: 50
      vip:
        max: 140
        min: 35
  total_count: 1000000
  type_distribution:
    corporate: 0.2
    personal: 0.8
  vip_ratio:
    corporate: 0.35
    personal: 0.15
data_correlation:
  account_transaction:
    account_type_transaction_influence:
      current:
        consumption_ratio: 0.65
      fixed:
        transfer_ratio: 0.7
    balance_transaction_correlation: 0.75
    historical_pattern_consistency: 0.65
  channel_behavior:
    channel_habit_stability: 0.8
    multichannel_conversion_increase: 0.25
    online_transaction_frequency_increase: 0.4
  customer_account:
    age_account_correlation:
      middle:
        fixed_preference: 0.6
      young:
        current_preference: 0.7
    corporate_size_account_correlation: 0.8
    high_value_multitype_probability: 0.8
  customer_product:
    age_product_correlation:
      elderly:
        stability_preference: 0.75
      young:
        high_return_preference: 0.65
    industry_loan_correlation: 0.7
    risk_preference_correlation:
      conservative:
        low_risk_product_ratio: 0.8
data_trend:
  decline:
    offline_counter:
      yearly_rate: -0.055
    paper_document:
      yearly_rate: -0.075
    traditional_deposit:
      yearly_rate: -0.02
  emerging:
    mobile_payment:
      yearly_rate: 0.2
    online_investment:
      yearly_rate: 0.15
    online_loan:
      yearly_rate: 0.25
  fluctuation:
    daily_fluctuation:
      max: 0.2
      min: 0.1
    seasonal_fluctuation:
      max: 0.3
      min: 0.15
    special_event_fluctuation:
      max: 1.0
      min: 0.5
  growth:
    customer_base:
      monthly_rate: 0.01
    electronic_channel:
      yearly_increase: 0.035
    transaction_volume:
      yearly_rate: 0.12
  noise:
    base_noise:
      max: 0.05
      min: 0.01
    channel_difference_noise:
      max: 0.08
      min: 0.03
    weekday_weekend_noise:
      max: 0.1
      min: 0.05
investment:
  actual_return:
    negative_return_probability:
      high_risk: 0.05
    variance:
      high_risk: 0.02
      low_risk: 0.005
      medium_risk: 0.01
  amount:
    corporate:
      max: 5000000
      mean: 1500000
      min: 500000
      std_dev: 1000000
    personal:
      max: 200000
      mean: 100000
      min: 50000
      std_dev: 50000
    vip_multiplier: 1.75
  channel_distribution:
    counter: 0.27
    mobile_app: 0.45
    online_banking: 0.28
  expected_return:
    high_risk:
      max: 0.12
      min: 0.07
    low_risk:
      max: 0.045
      min: 0.03
    medium_risk:
      max: 0.07
      min: 0.045
    term_adjustment:
      long: 0.015
      medium: 0.01
  risk_level_distribution:
    high: 0.2
    low: 0.45
    medium: 0.35
  term_distribution:
    long_term:
      days:
      - 540
      - 730
      - 1095
      ratio: 0.2
    medium_term:
      days:
      - 120
      - 180
      - 270
      - 365
      ratio: 0.45
    short_term:
      days:
      - 30
      - 60
      - 90
      ratio: 0.35
loan:
  approval_time:
    large:
      max_days: 15
      min_days: 7
    medium:
      max_days: 7
      min_days: 3
    small:
      max_days: 3
      min_days: 1
    vip_time_reduction: 0.3
  interest_rate:
    base_rate: 0.0325
    car:
      max_adjustment: 0.03
      min_adjustment: 0.01
    credit_score_impact: 0.2
    mortgage:
      max_adjustment: 0.01
      min_adjustment: 0.0
    personal_consumption:
      max_adjustment: 0.04
      min_adjustment: 0.02
    small_business:
      max_adjustment: 0.05
      min_adjustment: 0.03
  status_distribution:
    applying: 0.06
    approved: 0.04
    disbursed: 0.04
    overdue: 0.03
    rejected: 0.01
    repaying: 0.75
    settled: 0.07
  term_distribution:
    long_term:
      months:
      - 72
      - 84
      - 120
      - 180
      - 240
      - 300
      - 360
      ratio: 0.3
    medium_term:
      months:
      - 24
      - 36
      - 48
      - 60
      ratio: 0.45
    short_term:
      months:
      - 3
      - 6
      - 12
      ratio: 0.25
  type_distribution:
    car: 0.12
    education: 0.08
    mortgage: 0.3
    personal_consumption: 0.4
    small_business: 0.1
seasonal_cycle:
  daily_cycle:
    afternoon:
      ratio: 0.25
    early_morning:
      main_channel: mobile_app
      ratio: 0.05
    evening:
      main_type: personal
      ratio: 0.2
    morning:
      main_business: corporate
      ratio: 0.3
    night:
      main_channel: online
      ratio: 0.05
    noon:
      increase_consumption: true
      ratio: 0.15
  monthly_cycle:
    early_month:
      bill_payment: true
      ratio: 0.4
      salary_period: true
    end_month:
      corporate_settlement: true
      ratio: 0.35
    mid_month:
      balanced: true
      ratio: 0.25
    salary_effect:
      days_after: 3
      days_before: 1
      transaction_increase: 0.6
  quarterly_cycle:
    financial_report_period:
      corporate_activity_increase: 0.4
      days_after: 3
      days_before: 5
    quarter_end:
      corporate_volume_increase: 0.45
      large_transaction_increase: 0.3
    tax_filing_period:
      corporate_payment_increase: 0.5
  weekly_cycle:
    friday:
      consumption_increase: 0.15
      ratio: 0.2
      salary_day: true
    monday:
      corporate_ratio_increase: 0.15
      ratio: 0.18
    tuesday_thursday:
      balanced: true
      ratio: 0.17
    weekend:
      consumption_ratio_increase: 0.2
      ratio: 0.14
      volume_decrease: 0.35
  yearly_cycle:
    holidays:
      consumption_ratio_increase: 0.3
      volume_decrease: 0.4
    school_season:
      education_payment_concentration: 0.7
      months:
      - 2
      - 9
    spring_festival:
      deposit_increase: 0.6
      weeks_before: 4
      withdrawal_increase: 0.7
    summer_vacation:
      education_payment_increase: 0.45
      months:
      - 7
      - 8
      travel_consumption_increase: 0.35
    year_end:
      corporate_settlement_peak: 0.65
      month: 12
system:
  batch_size: 1000
  historical_end_date: '2025-04-03'
  historical_start_date: '2024-04-01'
  locale: zh_CN
  random_seed: 42
transaction:
  amount:
    corporate:
      large:
        range:
        - 100000
        - 1000000
        ratio: 0.2
      medium:
        range:
        - 10000
        - 100000
        ratio: 0.4
      small:
        range:
        - 1000
        - 10000
        ratio: 0.4
    personal:
      large:
        range:
        - 10000
        - 100000
        ratio: 0.1
      medium:
        range:
        - 1000
        - 10000
        ratio: 0.3
      small:
        range:
        - 100
        - 1000
        ratio: 0.6
  channel_distribution:
    atm: 0.18
    counter: 0.07
    mobile_app: 0.35
    online_banking: 0.3
    third_party: 0.1
  correlation:
    large_deposit:
      fixed_deposit_probability: 0.3
      investment_probability: 0.3
    month_start_end:
      bill_payment_increase: 0.45
    salary_deposit:
      consumption_increase: 0.5
      effect_days: 3
      withdrawal_increase: 0.5
  frequency:
    current:
      transactions_per_month:
        corporate:
          max: 70
          mean: 45
          min: 25
        personal:
          max: 30
          mean: 20
          min: 10
    fixed:
      transactions_per_quarter:
        corporate:
          max: 6
          mean: 4
          min: 2
        personal:
          max: 3
          mean: 2
          min: 1
    loan:
      payment_frequency: monthly
    vip_multiplier: 1.25
  time_distribution:
    weekend:
      afternoon:
        peak_time: '14:00'
        ratio: 0.45
      evening:
        peak_time: '19:30'
        ratio: 0.25
      morning:
        peak_time: '11:00'
        ratio: 0.25
      night:
        peak_time: '22:30'
        ratio: 0.05
    workday:
      afternoon:
        peak_time: '15:30'
        ratio: 0.3
      evening:
        peak_time: '19:00'
        ratio: 0.15
      lunch:
        peak_time: '13:00'
        ratio: 0.15
      morning:
        peak_time: '10:30'
        ratio: 0.35
      night:
        peak_time: '23:00'
        ratio: 0.05
    workday_ratio: 0.8
  type_distribution:
    consumption: 0.2
    deposit: 0.18
    other: 0.05
    transfer: 0.35
    withdrawal: 0.22
wechat_follower:
  campaign_participation:
    conversion_rate: 0.1
    participation_rate: 0.15
    transaction_probability_increase: 0.25
  follow_ratio:
    with_app: 0.55
    without_app: 0.15
  interaction_level:
    high:
      ratio: 0.25
      weekly_reading:
      - 1
      - 5
    low:
      ratio: 0.4
      yearly_reading:
      - 1
      - 12
    medium:
      monthly_reading:
      - 1
      - 3
      ratio: 0.35
